### ISSUE TITLE
Add a paper of instruction-guided video editing

### ISSUE THREAD

**Issue by ChenHsing** [wenhao728/awesome-diffusion-v2v#1]
Thanks for your awesome repo and survey. Could you please add our paper VIDiff (https://arxiv.org/abs/2311.18837) to the repo and following version survey?

**Comment by wenhao728** [comment]
Thanks for the reminder. I've added this work under "#Network and Training Paradigm / ##Training Modification". The section will be updated by next week. 

If you have any other recommended related methods or suggestions for improving the taxonomy, please let me know.

**Comment by wenhao728** [comment]
Updated in PR #4
