### ISSUE TITLE
Hi, can u add a novel multi-object editing method-EVA?

### ISSUE THREAD

**Issue by knightyxp** [wenhao728/awesome-diffusion-v2v#2]
https://github.com/user-attachments/assets/f0db1e62-e984-474f-a132-2f3f440c5451

Hi wenhao:

Glad to see the complex motion comparison and the new survey, I supplied an editing result in boxing-fisheye editing by our EVA(https://arxiv.org/abs/2403.16111),  we want to edit the blue head man -> Batman, mid man to Ironman,and  original green ring -> red ring,  EVA performs well in multi-attribute editing and multi-object editing, currently we already further improve the consistency, and the code will be released in the next month at https://github.com/knightyxp/EVA_Video_Edit. More result at https://knightyxp.github.io/EVA/, I hope you can add our paper in the survey, it belongs to the latent transition or attention feature modulation. Really appreciate!

**Comment by wenhao728** [comment]
Thank you for your valuable recommendation and insightful work. I plan to incorporate this paper into the repository in the next update (expected later this week) and upcoming revision of the paper.

**Comment by wenhao728** [comment]
Updated in PR #4
